// Mock data for demo mode
import { LOI } from './api';

export const mockLOIs: LOI[] = [
  {
    id: '1',
    teams_message_id: 'msg-001',
    teams_conversation_id: 'conv-001',
    customer: 'Lindt',
    product: 'Cocoa Butter',
    sku: 'CB-LIN-001',
    ratio: 2.78,
    incoterm: 'FOB',
    period: 'Jan-Jun 2026',
    quantity_mt: 100,
    quantity_unit: 'MT',
    currency: 'USD',
    sales_or_purchase: 'sales',
    ship_to_location: 'Europe',
    gross_ratio: 3.058,
    status: 'confirmed',
    created_by: 'John Smith',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    teams_message_id: 'msg-002',
    teams_conversation_id: 'conv-001',
    customer: 'Nestlé',
    product: 'Cocoa Powder',
    sku: 'CP-NES-002',
    ratio: 3.45,
    incoterm: 'CIF',
    period: 'Q1 2026',
    quantity_mt: 250,
    quantity_unit: 'MT',
    currency: 'EUR',
    sales_or_purchase: 'sales',
    ship_to_location: 'Europe',
    gross_ratio: 3.992,
    status: 'confirmed',
    created_by: 'Sarah Johnson',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    teams_message_id: 'msg-003',
    teams_conversation_id: 'conv-002',
    customer: 'Ferrero',
    product: 'Cocoa Nibs',
    sku: 'CN-FER-003',
    ratio: 2.15,
    incoterm: 'FOB',
    period: 'H2 2026',
    quantity_mt: 150,
    quantity_unit: 'MT',
    currency: 'EUR',
    sales_or_purchase: 'purchase',
    ship_to_location: 'Europe',
    gross_ratio: 2.365,
    status: 'modified',
    created_by: 'Mike Chen',
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    teams_message_id: 'msg-004',
    teams_conversation_id: 'conv-001',
    customer: 'Hershey',
    product: 'Cocoa Liquor',
    sku: 'CL-HER-004',
    ratio: 4.20,
    incoterm: 'CFR',
    period: 'Feb-Apr 2026',
    quantity_mt: 300,
    quantity_unit: 'MT',
    currency: 'USD',
    sales_or_purchase: 'sales',
    ship_to_location: 'Americas',
    gross_ratio: 4.536,
    status: 'confirmed',
    created_by: 'Emma Wilson',
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    teams_message_id: 'msg-005',
    teams_conversation_id: 'conv-003',
    customer: 'Mars',
    product: 'Cocoa Butter',
    sku: 'CB-MAR-005',
    ratio: 2.90,
    incoterm: 'FOB',
    period: 'Q2-Q3 2026',
    quantity_mt: 200,
    quantity_unit: 'MT',
    currency: 'USD',
    sales_or_purchase: 'purchase',
    ship_to_location: 'Asia',
    gross_ratio: 3.045,
    status: 'draft',
    created_by: 'David Lee',
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockModificationHistory = [
  {
    id: 1,
    loi_id: '3',
    modified_by: 'Mike Chen',
    modified_source: 'teams' as const,
    changes: { ratio: 2.15, status: 'modified' },
    modified_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    loi_id: '2',
    modified_by: 'Sarah Johnson',
    modified_source: 'web' as const,
    changes: { quantity_mt: 250 },
    modified_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

